'use strict';

// Equipment arranged in « ensembles » (the big thing, with its place on the plan) and « éléments » (what is set,
// breaks or is changed separately), as validated by the user (docs/EQUIPEMENTS-ENSEMBLES.md, generated by
// tools/equipment-groups-doc.js). Applied once by the content patch « 2026-10-28-ensembles »: existing equipment
// keeps its id (customers, diagnostics, lists and banners keep working), new ensembles and elements are created.
//
// Ensemble: { id, cat, name (new or renamed), new, note, alt, picks: { key: question }, kids: [...] }.
// Element (kid): { id, role, ... }
//   role always : comes with the ensemble (ticking the ensemble ticks it; « impl: false » when another element
//                 already brings it, e.g. the Truma plate comes with the Truma Combi);
//   role option : ticked only if the vehicle has it;
//   role pick   : one among the elements of the same « pick » key (batteries: AGM, GEL or lithium).
//   variant     : the model, asked as a choice (never guessed, « Je ne sais pas » always offered); only added when
//                 the element has no question yet.
//   dated       : a date read on the part, reminded in the maintenance logbook:
//                 until = end of validity written on it; made = manufacturing date, valid « years » after it;
//                 every = to change every « months ».
// Items the user dropped stay in the database (old data) but are hidden from the app: HIDE.

const A = (id, extra = {}) => ({ id, role: 'always', ...extra });
const O = (id, extra = {}) => ({ id, role: 'option', ...extra });
const P = (id, pick, extra = {}) => ({ id, role: 'pick', pick, ...extra });
const NEW = (name, text, extra = {}) => ({ new: true, name, text, ...extra });

const GROUPS = [
  // ---------- Cabine et conduite ----------
  { id: 'sieges', cat: 'cab', kids: [A('ceint'), O('sieges_chauf'), O('isofix')] },
  {
    id: 'occult', cat: 'cab',
    kids: [O('store_pb'), O('occult_rideaux', NEW('Rideaux de cabine', 'Rideaux tirés devant le pare-brise et les vitres avant pour la nuit.')),
      O('occult_isolants', NEW('Isolants à poser', 'Isolants souples à poser sur les vitres de la cabine, dedans ou dehors : moins de froid, moins de buée.'))],
  },
  {
    id: 'g_conduite', cat: 'cab', new: true, name: 'Aides à la conduite', text: 'Ce qui aide à conduire votre véhicule : régulateur, boîte automatique, caméra de recul, aides au freinage…',
    kids: ['regul', 'auto', 'frein_elec', 'start_stop', 'aides_cond', 'esp', 'traction', 'camera', 'retro_elec', 'pare_brise_ch', 'airbags'].map((id) => O(id)),
  },
  { id: 'radio', cat: 'cab', kids: [O('gps'), O('appli_veh')] },

  // ---------- Salon, couchage, rangements ----------
  {
    id: 'g_salon', cat: 'conf', new: true, name: 'Salon et dinette', text: 'L’espace repas : table, banquette, et selon le modèle un couchage d’appoint.',
    picks: { salon: 'Forme du salon' },
    kids: [A('table'), A('banq'), P('salon_l', 'salon'), P('salon_ar', 'salon'), O('dinette_lit'), O('table_elev'), O('table_ext'), O('fen')],
  },
  { id: 'lit_ar', cat: 'conf', picks: { lit: 'Type de lit' }, kids: [P('lit_central', 'lit'), P('lits_jum', 'lit'), P('superp', 'lit'), P('litar', 'lit'), O('lit_haut')] },
  { id: 'pavillon', cat: 'conf', kids: [O('lits_jum_pav'), O('echelle_lit')] },
  { id: 'lit_cap', cat: 'conf', kids: [O('fen_cap')] },
  {
    id: 'g_soute', cat: 'conf', new: true, name: 'Soute ou garage arrière', text: 'Le grand rangement à l’arrière, accessible par l’extérieur.',
    picks: { soute: 'Type' },
    kids: [P('soute', 'soute'), P('garage', 'soute'), O('trappe_int'), O('soute_trav'), O('arrimage')],
  },
  { id: 'plac', cat: 'conf', kids: [O('plac_ar'), O('penderie')] },
  { id: 'toit_rel', cat: 'ext', kids: [A('lit_toit')] },

  // ---------- Cuisine ----------
  { id: 'rechaud', cat: 'cui', kids: [O('dessous_plaque', { note: 'Seulement si on peut le photographier.' }), O('hotte')] },
  { id: 'evier', cat: 'cui', kids: [A('siphon_cui')] },
  { id: 'frigo', cat: 'cui', name: 'Réfrigérateur', kids: [A('frigo_plaque')] },

  // ---------- Salle d'eau ----------
  {
    id: 'wc', cat: 'sdb',
    kids: [A('cassette', NEW('Cassette', 'Le réservoir amovible des toilettes, qu’on vide sur une borne par la trappe extérieure.')),
      A('chasse', { variant: { q: 'Chasse d’eau', o: ['Sur l’eau propre du véhicule', 'Réservoir de chasse séparé'] } }), A('vanne_wc'),
      A('wc_niveau', NEW('Indicateur de niveau', 'Le voyant qui prévient quand la cassette est presque pleine.')),
      O('wc_ventil', NEW('Ventilation anti-odeur', 'Petit ventilateur qui aspire les odeurs de la cassette vers l’extérieur.')),
      O('wc_roulettes', NEW('Cassette à roulettes et poignée', 'La cassette se tire comme une valise jusqu’à la borne.')),
      O('wc_cassette2', NEW('Deuxième cassette', 'Une cassette de rechange pour durer plus longtemps sans vidanger.'))],
  },
  { id: 'wc_noires', cat: 'sdb', kids: [A('noires_vanne', NEW('Vanne de vidange des eaux noires', 'La vanne qu’on ouvre sur une plateforme de vidange pour vider le réservoir des toilettes.'))] },
  {
    id: 'douche', cat: 'sdb', picks: { sdb: 'Forme de la salle d’eau' },
    kids: [A('lavabo'), A('siphon_sdb'), A('colonne'), A('bonde_douche'), A('champ'), P('douche_sep', 'sdb'), P('sdb_mod', 'sdb'), P('sdb_trav', 'sdb'), O('caillebotis')],
  },

  // ---------- Eau ----------
  { id: 'propre', cat: 'eau', name: 'Circuit d’eau propre', kids: [A('pompe'), O('filtre', { dated: { kind: 'every', months: 6, label: 'Cartouche du filtre à changer' } }), O('dext')] },
  { id: 'grises', cat: 'eau', kids: [O('antigel')] },

  // ---------- Gaz ----------
  {
    id: 'coffre_gaz', cat: 'gaz', name: 'Coffre à gaz (bouteilles)', alt: 'gaz',
    kids: [
      A('lyre', NEW('Lyre', 'Le tuyau souple entre la bouteille et le détendeur. Sa date limite est marquée dessus : au-delà, on la change.', { dated: { kind: 'until', label: 'Date limite marquée sur la lyre' } })),
      A('detendeur', NEW('Détendeur', 'Il abaisse la pression du gaz de la bouteille pour les appareils. Sa date de fabrication est marquée dessus : il se change 10 ans après.', {
        variant: { q: 'Modèle de détendeur', o: ['Détendeur simple sur la bouteille', 'Truma Duocontrol', 'Truma Duocontrol CS', 'Truma Monocontrol CS', 'Autre inverseur automatique'] },
        dated: { kind: 'made', years: 10, label: 'Date de fabrication marquée sur le détendeur' },
      })),
      A('bouteille', { name: 'Bouteilles de gaz' }),
    ],
  },
  {
    id: 'gaslow', cat: 'gaz', name: 'Coffre GPL (réservoir fixe ou bouteilles rechargeables)', alt: 'gaz', note: 'Pas de date de validité à suivre.',
    variant: { q: 'Type', o: ['Réservoir fixe', 'Bouteilles rechargeables'] },
    kids: [A('gpl_coupelle', NEW('Coupelle de remplissage', 'L’embout extérieur où l’on branche le pistolet de GPL à la station.')),
      O('gpl_adaptateurs', NEW('Adaptateurs de remplissage pour l’étranger', 'Chaque pays a son pistolet : ces adaptateurs permettent de faire le plein de GPL partout en Europe.')),
      O('gazext')],
  },

  // ---------- Électricité et énergie ----------
  {
    id: 'g_batterie', cat: 'elec', new: true, name: 'Batterie cellule', text: 'La batterie qui alimente la cellule (éclairage, pompe, chauffage…) quand vous n’êtes pas branché.',
    picks: { bat: 'Type de batterie' },
    kids: [P('agm', 'bat'), P('gel', 'bat'), P('lith', 'bat'), O('coupe'), O('bat2'), O('moni'), O('b2b')],
  },
  {
    id: 'quai', cat: 'elec', name: 'Prise P17 et circuit 230 V',
    kids: [A('disj'), A('charg'), A('prises230', NEW('Prises 230 V intérieures', 'Les prises de courant de la cellule.', { note: 'Elles ne marchent que si la prise P17 extérieure est branchée, sauf avec un convertisseur (onduleur) installé pour les alimenter.' })),
      O('onduleur'), O('p230')],
  },
  { id: 'panneau', cat: 'elec', kids: [O('gest_energie')] },
  { id: 'solaire', cat: 'elec', kids: [A('mppt', { name: 'Régulateur solaire', variant: { q: 'Type de régulateur', o: ['MPPT', 'PWM'] } })] },

  // ---------- Chauffage, climat, aération ----------
  {
    id: 'g_chauffage', cat: 'chauf', new: true, name: 'Chauffage de la cellule', text: 'Le chauffage de la cellule et ses sorties d’air chaud.',
    picks: { chauf: 'Modèle de chauffage' },
    kids: [P('trumac', 'chauf'), P('trumad', 'chauf'), P('webasto', 'chauf'), P('alde', 'chauf'), P('combi', 'chauf'), A('cmd_chauf'), A('gaines'),
      A('evac_truma', { impl: false }), A('truma_plaque', { impl: false }), A('gaine_cell', { impl: false }), A('gaine_sdb', { impl: false }), A('gaine_soute', { impl: false }),
      O('plancher'), O('appoint')],
  },
  {
    id: 'g_eauchaude', cat: 'chauf', new: true, name: 'Chauffe-eau séparé', text: 'Le chauffe-eau, quand l’eau chaude n’est pas faite par le chauffage (Truma Combi, Alde).',
    picks: { eau: 'Chauffe-eau' }, kids: [P('trumae', 'eau'), P('eaue', 'eau')],
  },
  { id: 'clim', cat: 'chauf', note: 'Elle ne marche que branchée sur le 230 V (prise P17).', kids: [O('clim_telec', NEW('Télécommande de la climatisation', 'La télécommande de la climatisation de toit.'))] },
  {
    id: 'clim_soute', cat: 'chauf', new: true, name: 'Climatisation de soute ou de coffre', spotFrom: 'soute', note: 'Elle ne marche que branchée sur le 230 V (prise P17).',
    text: 'Climatiseur installé sous une banquette ou dans un coffre : le toit reste libre et il est plus silencieux.',
    kids: [A('clim_soute_filtre', NEW('Filtre à air de la climatisation', 'Le filtre sur l’aspiration d’air : à nettoyer ou changer chaque année.', { dated: { kind: 'every', months: 12, label: 'Filtre à nettoyer ou changer' } })),
      O('clim_soute_telec', NEW('Télécommande de la climatisation de soute', 'La télécommande de la climatisation de soute.'))],
  },
  {
    id: 'rafraich', cat: 'chauf', new: true, name: 'Rafraîchisseur d’air de toit (12 V)', spotFrom: 'lant', note: 'Il marche sur la batterie (12 V), sans prise.',
    text: 'Ventilateur de toit qui rafraîchit l’air en marchant sur la batterie.',
    kids: [O('rafraich_telec', NEW('Télécommande du rafraîchisseur', 'La télécommande du rafraîchisseur d’air de toit.'))],
  },
  {
    id: 'g_lanterneaux', cat: 'chauf', new: true, name: 'Lanterneaux (skydomes)', spotFrom: 'lant', text: 'Les ouvertures du toit qui éclairent et aèrent la cellule. Cochez ceux de votre véhicule.',
    kids: ['lant', 'lant_lit', 'lant_cui', 'lant_sdb', 'lant_cap', 'lant_pav', 'heki', 'maxx'].map((id) => O(id)),
  },

  // ---------- Extérieur ----------
  {
    id: 'store', cat: 'ext',
    kids: [A('store_toile', NEW('Toile et bras du store', 'La toile et les bras articulés qui la tendent.')),
      O('store_cotes', NEW('Côtés du store (panneaux latéraux)', 'Panneaux qui ferment les côtés du store contre le vent et le soleil.')),
      O('store_tempete', NEW('Kit tempête du store', 'Sangles et piquets qui tiennent le store au sol quand le vent se lève.')),
      O('store_led', NEW('Éclairage LED du store', 'Bandeau lumineux le long du store.')),
      O('store_vent', NEW('Capteur de vent du store', 'Il fait rentrer le store motorisé tout seul quand le vent est trop fort.'))],
  },
  { id: 'porte_cell', cat: 'ext', kids: [O('porte_moust', NEW('Moustiquaire de porte', 'La moustiquaire de la porte de la cellule.')), O('gouttiere')] },
  { id: 'porte', cat: 'ext', kids: [O('moust_lat')] },
  { id: 'portes_ar', cat: 'ext', kids: [O('fen_ar'), O('rideau_ar')] },
  { id: 'marche_ext', cat: 'ext', kids: [A('marche')] },
  { id: 'galerie', cat: 'ext', kids: [O('echelle')] },

  // ---------- Châssis et suspension ----------
  {
    id: 'g_roues', cat: 'chas', new: true, name: 'Pneus et roues', text: 'Les pneus et la solution en cas de crevaison.',
    kids: [A('pneus', { dated: { kind: 'made', years: 6, label: 'Date de fabrication sur le flanc (4 chiffres : semaine et année)' } }),
      A('secours', { variant: { q: 'En cas de crevaison', o: ['Roue de secours', 'Kit anti-crevaison'] } }), O('pneus_hiver')],
  },
  { id: 'g_niveau', cat: 'chas', new: true, name: 'Mise à niveau et stabilisation', text: 'Ce qui met le véhicule à plat et le stabilise à l’arrêt.', kids: [O('cales'), O('bequilles'), O('verins')] },

  // ---------- Multimédia ----------
  {
    id: 'satman', cat: 'multi', alt: 'sat',
    kids: [A('pointeur_sat', NEW('Pointeur satellite', 'Le petit boîtier qui bipe quand l’antenne est bien tournée vers le satellite.')),
      A('demod_man', NEW('Démodulateur satellite', 'Le boîtier qui reçoit les chaînes, avec sa carte TNTSAT ou FRANSAT.'))],
  },
  {
    id: 'sat', cat: 'multi', alt: 'sat',
    kids: [A('sat_cmd', NEW('Boîtier de commande de l’antenne', 'Il fait tourner et pointer l’antenne automatique vers le satellite.')),
      A('demod_auto', NEW('Démodulateur de l’antenne automatique', 'Le boîtier qui reçoit les chaînes, avec sa carte TNTSAT ou FRANSAT.', { note: 'Parfois intégré au boîtier de commande ou au téléviseur.' }))],
  },
  { id: 'tnt', cat: 'multi', kids: [A('tnt_ampli', NEW('Amplificateur de signal TNT', 'Il renforce le signal de l’antenne hertzienne. Il a souvent un bouton ou un voyant à allumer.'))] },
  { id: 'tv', cat: 'multi', variant: { q: 'Combien de téléviseurs ?', o: ['Un', 'Deux', 'Trois ou plus'] }, kids: [] },

  // ---------- Sécurité ----------
  {
    id: 'g_detecteurs', cat: 'secu', new: true, name: 'Détecteurs', text: 'Les détecteurs qui veillent pendant que vous dormez.',
    kids: [O('fumee', { dated: { kind: 'made', years: 10, label: 'Date de fabrication au dos du détecteur' } }), O('co', { dated: { kind: 'until', label: 'Date de fin de vie marquée au dos' } }), O('gazdet'), O('gazsop')],
  },
  { id: 'extinct', cat: 'secu', dated: { kind: 'until', label: 'Date de validité ou de prochain contrôle sur l’étiquette' }, kids: [] },
  { id: 'g_antivol', cat: 'secu', new: true, name: 'Antivol', text: 'Ce qui protège le véhicule contre le vol.', kids: [O('alarme'), O('traceur'), O('coffre_fort')] },
  {
    id: 'g_bord', cat: 'secu', new: true, name: 'Équipement de bord', text: 'Ce qu’il faut avoir à bord en cas de panne ou d’accident.',
    kids: [A('gilet'), O('trousse', { dated: { kind: 'until', label: 'Date de péremption des produits' } })],
  },
];

// Dropped by the user: kept in the database for old data, never shown.
// chauf and eauch: the old general « Chauffage de la cellule » and « Eau chaude », replaced by the ensembles (they stay
// behind the scenes for the diagnostics).
// duo: the automatic changeover is a model of regulator (Duocontrol…), asked under « Détendeur ».
const HIDE = ['cuis_l', 'cell', 'tpms', 'vue_ar', 'tech_vue', 'chauf', 'eauch', 'duo'];
// Photos of the vehicle stored as equipment: hidden from the lists, still shown in their zone of the plan.
const PHOTO_VIEWS = ['vue_ar', 'tech_vue'];

module.exports = { GROUPS, HIDE, PHOTO_VIEWS };
